import configobj
import sys
import os

# TODO: This file should be autogenerated so I don't have to type all of the
# variables names over and over.

LOADED = False
CONFIG_FILE = '/home/sambryant/bin/github_projects/pi-server/conf_files/pi-server-client.conf'
DEFAULT_SECTION = 'DEFAULT'

DryRun = False

def set_dryrun(dryrun):
  global DryRun
  DryRun = dryrun

def load(no_reload=False):
  if no_reload and LOADED:
    return
  config = configobj.ConfigObj(CONFIG_FILE)[DEFAULT_SECTION]
  global ClientProjectDir, ServerHostname, ServerLocalname, ServerUser, ServerDataDrive, ServerBackupDrive, ServerLogScript, ServerProjectDir, RsyncDelete, RsyncVerbose, NotifyDesktop, NotifySyslog, NotifyServerLog, NotifyDesktopExpireTime
  ClientProjectDir = config['ClientProjectDir']
  ServerHostname = config['ServerHostname']
  ServerLocalname = config['ServerLocalname']
  ServerUser = config['ServerUser']
  ServerDataDrive = config['ServerDataDrive']
  ServerProjectDir = config['ServerProjectDir']
  ServerBackupDrive = config['ServerBackupDrive']
  ServerLogScript = config['ServerLogScript']
  RsyncDelete = config['RsyncDelete']
  RsyncVerbose = config['RsyncVerbose']
  NotifyDesktop = config['NotifyDesktop']
  NotifySyslog = config['NotifySyslog']
  NotifyServerLog = config['NotifyServerLog']
  NotifyDesktopExpireTime = config['NotifyDesktopExpireTime']
  loaded = True

def write_defaults():
  config = configobj.ConfigObj()
  config[DEFAULT_SECTION] = {
    'ClientProjectDir': '/home/sambryant/bin/github_projects/pi-server',
    'ServerHostname': 'sjb-pi-ext',
    'ServerLocalname': 'sjb-pi',
    'ServerUser': 'sambryant',
    'ServerDataDrive': '/drives/data',
    'ServerBackupDrive': '/drives/backup',
    'ServerProjectDir': '/drives/data/pi-server',
    'ServerLogScript': 'src/server/log_server.py',
    'RsyncDelete': True,
    'RsyncVerbose': True,
    'NotifyDesktop': True,
    'NotifyServerLog': True,
    'NotifySyslog': True,
    'NotifyDesktopExpireTime': 4000
  }
  config.filename = CONFIG_FILE
  config.write()
  #with open('conf.ini', 'w') as configfile:
  #  config.write(configfile)

if __name__ == '__main__':
  write_defaults()